services:
  - type: web
    name: auth-server
    env: node
    root: apps/auth-server
    buildCommand: pnpm install --frozen-lockfile && pnpm run generate && pnpm run build
    startCommand: pnpm run start
    plan: free